### ISSUE TITLE
npm build && npm start does not render <ix-img> on initial load (Nuxt.js typescript)

### ISSUE THREAD

**Issue by AndersNielsen85** [imgix/vue-imgix#162]
I am experiencing a problem loading the images on the initial load.

If I run "npm run dev", everything seems to work just fine.
But if I run "npm build && npm start" the image does not load on the initial page load. After switching routes and going back the image will load.

Running Nuxt.js with typescript, with standard configuration copied from the readme.
![image](https://user-images.githubusercontent.com/48467762/87636452-0fcb3a00-c741-11ea-9a9d-408b88e72319.png)

Code:
`      <ix-img
        src="femina/s3fs-public/media/article/renee-6_1.png"
        :imgixParams="{ ar: '414:548', fit: 'crop' }"
        width="414"
        height="548"
        alt="Some alt text"
      />`

Screenshot of initial load:
![image](https://user-images.githubusercontent.com/48467762/87635979-3b015980-c740-11ea-80e3-067adcd8dce0.png)

**Comment by frederickfogerty** [comment]
Hey @AndersNielsen85 - Fred here, the creator of this library. Thanks for opening this issue (and the other one).

Firstly, sorry that you had to go through this issue. Nuxt.js is definitely something we want to have first-class support for, so this is something we'll be investigating.

I've been able to replicate this issue in [a CodeSandbox](https://codesandbox.io/s/hungry-cookies-nlop0), so this is a good start. I'll be doing more work to investigate why this is happening here. While I'm doing this, I was wondering if you had any information about either a) any possible causes for this, b) an explanation for the different behaviour between Nuxt.js during server rendering and client rendering, and c) any tips for debugging this sort of issue? Since I don't have any experience with Nuxt.js, any of this would be greatly helpful to getting this resolved sooner.

Anyway, I'll keep this thread updated with any progress on this issue.

**Comment by frederickfogerty** [comment]
@AndersNielsen85 are you able to let me know what device you're experiencing these errors on? I'm on a Mac and although I can reproduce this in the CodeSandbox, I can reproduce this locally.

**Comment by frederickfogerty** [comment]
Hi @AndersNielsen85, I have realised that the issue here was that the suggested config for Nuxt.js only specified the plugin to work on the client. If this doesn't fix your issue, please comment here or open another issue. At this stage, this is resolved.
