### ISSUE TITLE
Failed to resolve directive: lozad (Nuxt 2.14)

### ISSUE THREAD

**Issue by lmuzquiz** [imgix/vue-imgix#356]
### How to recreate this issue:

Create a fresh Nuxt 2 project with **yarn add nuxt** and then **yarn add vue-imgix** according to the instructions on how to install vue-imgix on NUXT. (i was using Node: 12.18 and npm: 6.14)

Then follow the instructions on this github repo for adding Lozad. 

Example code:

![Screen Shot 2021-01-04 at 13 48 41](https://user-images.githubusercontent.com/11865448/103573267-93b1e380-4e93-11eb-84b2-77086ae7fdf8.png)

You will get an error on the console: 

![Screen Shot 2021-01-04 at 13 49 18](https://user-images.githubusercontent.com/11865448/103573325-aaf0d100-4e93-11eb-996f-97713e365ae3.png)

**Comment by lmuzquiz** [comment]
I could make it work by adding: https://github.com/ax2inc/lozad-module and then doing these two changes:

<img width="824" alt="Screen Shot 2021-01-04 at 14 25 48" src="https://user-images.githubusercontent.com/11865448/103576457-cad6c380-4e98-11eb-8159-7a1cec6891f1.png">

please notice v-lozad was removed

**Comment by frederickfogerty** [comment]
Hey there, thanks for the issue @lmuzquiz! Unfortunately the instructions might not have been clear enough for the Lozad example - the code is not meant to be executed in the `mounted()` lifecycle event, but rather in the Vue setup code (e.g. in `src/main.js`). I've updated the documentation to reflect this in #358.

Also, I didn't test this directive with Nuxt, so thank you for the extra information on how to make it working. Unfortunately since the code is now explicitly using Lozad, it can't take advantage of native lazy-loading, which is half the advantage of the original directive. 

I'll take a look at this at some stage and see if I can rework the snippet to work with Nuxt too.

**Comment by lmuzquiz** [comment]
> Hey there, thanks for the issue @lmuzquiz! Unfortunately the instructions might not have been clear enough for the Lozad example - the code is not meant to be executed in the `mounted()` lifecycle event, but rather in the Vue setup code (e.g. in `src/main.js`). I've updated the documentation to reflect this in #358.
> 
> Also, I didn't test this directive with Nuxt, so thank you for the extra information on how to make it working. Unfortunately since the code is now explicitly using Lozad, it can't take advantage of native lazy-loading, which is half the advantage of the original directive.
> 
> I'll take a look at this at some stage and see if I can rework the snippet to work with Nuxt too.

Thanks @frederickfogerty , hope you could add a brief Nuxt example to your docs, since it's quite popular these days.

**Comment by frederickfogerty** [comment]
For sure @lmuzquiz. We're also hoping to release a more powerful Nuxt-specific version of this library at some point too, so keep an eye out for that 😄

**Comment by lmuzquiz** [comment]
Looking forward to it
