### ISSUE TITLE
Not possible to Sign URLs which makes impossible to use Web Proxy Sources

### ISSUE THREAD

**Issue by Tiagogv** [imgix/vue-imgix#411]
The js-core client allows to set the Secure URL Token, but it's not being set when using this lib.

This option should be pass on when creating the client in VueImgixClient constructor.

[Web Proxy Sources](https://github.com/imgix/js-core#web-proxy-sources)

**Comment by frederickfogerty** [comment]
Hi @Tiagogv, thanks for the issue! Since Vue works on the frontend, it would create a security vulnerability to serve the secure URL token in the JS bundle as this would allow a malicious user to proxy any image through your account, costing you potentially lots of money! Thus, this feature is not supported for this library. The js-core client supports it, because it is also used on the server, where it is possible to use this feature safely.

If you are doing server-side rendering, we advise you to use our js-core library to create your own images, or see [here](https://github.com/imgix/react-imgix/issues/580#issuecomment-656260302) for some other ideas in how to support Web Proxy Sources in React, another client-side library. The solutions proposed there would also work in Vue.

Hope this helps!

**Comment by Tiagogv** [comment]
Thanks for the answer. I get the security issue, but if using NuxtJs for generating a static website this would be very useful since the security token would only be available while generating the website and not on the deployed files.

**Comment by frederickfogerty** [comment]
That is a fair point. I will raise this internally and see if we can prioritise this at some point. 

For now I would recommend you to find a workaround by either forking this repo and modifying the source code to work for you, or by using js-core directly. As you have already found, you could modify the source code [here](https://github.com/imgix/vue-imgix/blob/main/src/plugins/vue-imgix/vue-imgix.ts#L29-L32) to pass through the `secureURLToken`.

Let me know how it goes and if I can help any more.

**Comment by joevandyk** [comment]
Any update on this?

**Comment by frederickfogerty** [comment]
Hi @joevandyk, can you please provide some more details on the specific use case you have and the issue you're encountering? Thanks!
